### ISSUE TITLE
Repo deprecated?

### ISSUE THREAD

**Issue by haricane8133** [Netflix/conductor-ui#3]
Is this repo deprecated compared to https://github.com/Netflix/conductor/tree/main/ui?

**Comment by peterlau** [comment]
This repo is primarily used by the Netflix internally. We work on a branch that has significant differences and would not be compatible with the open source API. 

It still remains a goal to switch to this repo as the source-of-truth for the UI code. However, it is`Netflix/conductor` that is being maintained actively in terms of OSS contributions, so I would create PR's against `/ui` in that project for the time being. 
 
I'll find some time to automate harmonizing the `main` branch here with that project to maintain consistency.
